docker rm -f security_front_admin
docker rm -f security_back_admin
docker rm -f security_front_user
docker rm -f security_back_user
docker rm -f apigw
docker rm -f eureka
docker rm -f data-service-broker
docker rm -f push-agent
docker rm -f data-manager
docker rm -f ingest-interface
docker rm -f datacore-ui
docker rm -f datacore-usertool
docker rm -f cp-kafka-rest
docker rm -f cp-kafka
docker rm -f cp-zookeeper
docker rm -f rabbitmq
docker rm -f ingest-web
docker rm -f ingest-daemon
docker rm -f pgsql
