docker load -i ../deploy/tar/apigw.tar
docker load -i ../deploy/tar/security_front.tar
docker load -i ../deploy/tar/security_back.tar
docker load -i ../deploy/tar/ingest-daemon.tar
docker load -i ../deploy/tar/ingest-web.tar
docker load -i ../deploy/tar/ingest-interface.tar
docker load -i ../deploy/tar/datacore-ui.tar
docker load -i ../deploy/tar/data-service-broker.tar
docker load -i ../deploy/tar/datacore-ui.tar
docker load -i ../deploy/tar/data-manager.tar
docker load -i ../deploy/tar/push-agent.tar
docker load -i ../deploy/tar/datacore-usertool.tar
docker load -i ../deploy/tar/postgresql.tar
docker load -i ../deploy/tar/eureka.tar